apiVersion: v1
kind: Secret
metadata:
  name: swiftpay-secret
  namespace: swiftpay
type: Opaque
stringData:
  POSTGRES_USER: swiftpay
  POSTGRES_PASSWORD: swiftpay

  CLICKHOUSE_USER: swiftpay
  CLICKHOUSE_PASSWORD: swiftpay